version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=s3,sqs,dynamodb,lambda,apigateway
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: .
    volumes:
        - .:/src
        - nodemodules:/src/node_modules
    restart: on-failure
      # command: npm test
    ports:
      - 3000:3000
    links:
      - localstack
    depends_on: 
      - localstack
    environment: 
      LOCALSTACK_HOST: localstack
      S3_PORT: 4572
      SQS_PORT: 4576
      REGION: us-east-1

volumes:
    nodemodules: {}